name: 'Run action'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'dist/**'
      - 'package*.json'
      - 'action.json'

jobs:
  setup-version2:
    name: 'Setup version'

    strategy:
      matrix:
        system:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.system }}

    steps:
      - name: Setup Conan
        id: setup-conan
        uses: imesense/gha-setup-conan@bd40f27516eaf99b8d9e36162fad22b00aaeed12
        with:
          version: '2.5.0'

      - name: Print version
        run: |
          conan --version

  setup-latest:
    name: 'Setup latest'

    strategy:
      matrix:
        system:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.system }}

    steps:
      - name: Setup Conan
        id: setup-conan
        uses: imesense/gha-setup-conan@bd40f27516eaf99b8d9e36162fad22b00aaeed12

      - name: Print version
        run: |
          conan --version
